export const TYPES = {
  // PRISMA
  PRISMA_CONNECTION: Symbol('PRISMA_CONNECTION'),
  // USE CASES
  CREATE_USER_CASE: Symbol('CREATE_USER_CASE'),
  UPDATE_USER_CASE: Symbol('UPDATE_USER_CASE'),
  FIND_USERS_CASE: Symbol('FIND_USERS_CASE'),
  FIND_ONE_USER_CASE: Symbol('FIND_ONE_USER_CASE'),
  DELETE_USER_CASE: Symbol('DELETE_USER_CASE'),

  // REPOSITORIES
  USER_REPOSITORY: Symbol('USER_REPOSITORY'),
}
